name: Scrape latest data
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,17,26,46,57 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.2
      with:
        path: |
          ./venv
          ./pha*
        key: venv
    - name: Fetch latest data
      env:
        TESTING: ${{ secrets.TESTING}}
        NYT_TWITTER_CONSUMER_KEY: ${{ secrets.NYT_TWITTER_CONSUMER_KEY}}
        NYT_TWITTER_CONSUMER_SECRET: ${{ secrets.NYT_TWITTER_CONSUMER_SECRET}}
        NYT_TWITTER_ACCESS_TOKEN: ${{ secrets.NYT_TWITTER_ACCESS_TOKEN}}
        NYT_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.NYT_TWITTER_ACCESS_TOKEN_SECRET}}
        NYT_API_KEY: ${{ secrets.NYT_API_KEY}}
        RSS_URL: ${{ secrets.RSS_URL}}
        PHANTOMJS_PATH: ${{ secrets.PHANTOMJS_PATH}}
      run: |-
        envsubst < run_diff.sh > run.sh
        bash run.sh | tee log.txt
    - name: LOG
      run: cat log.txt
    - name: Save log
      uses: actions/upload-artifact@v2.1.4
      with:
        name: log
        path: log.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add titles.db
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
